/**
 * Single source of truth for every route path string mounted under each
 * feature router. Route files import their namespaced slice from here
 * instead of declaring a local `*_ROUTES` const. Mechanical only — path
 * strings must not change when migrating a route file to use this.
 */
export const END_POINTS = {
  auth: {
    login: "/login",
    refresh: "/refresh",
    logout: "/logout",
    me: "/me",
  },
  asset: {
    listMachines: "/machines",
    createMachine: "/machines",
    updateMachine: "/machines/:id",
    listItems: "/items",
    createItem: "/items",
    updateItem: "/items/:id",
    lastRate: "/items/:itemId/last-rate",
    listServices: "/services",
    createService: "/services",
    updateService: "/services/:id",
    listInventoryMovements: "/inventory/movements",
    createInventoryMovements: "/inventory/movements",
    listLocations: "/locations",
    createLocation: "/locations",
    updateLocation: "/locations/:id",
  },
  setup: {
    modules: {
      list: "/modules",
    },
    employees: {
      list: "/employees",
      search: "/employees/search",
      create: "/employees",
      update: "/employees/:id",
      remove: "/employees/:id",
      generateQr: "/employees/:id/qr",
      assignableRoles: "/employees/assignable-roles",
      assignRole: "/employees/:id/role",
    },
    roles: {
      list: "/roles",
      create: "/roles",
      update: "/roles/:id",
      remove: "/roles/:id",
      copy: "/roles/:id/copy",
      getGrants: "/roles/:id/grants",
      setGrants: "/roles/:id/grants",
    },
    screens: {
      list: "/screens",
      update: "/screens/:key",
      setRoles: "/screens/:key/roles",
    },
    accessLog: {
      list: "/access-log",
    },
    pages: {
      list: "/pages",
      create: "/pages",
      update: "/pages/:id",
      remove: "/pages/:id",
    },
    permissions: {
      list: "/permissions",
      updateForRole: "/roles/:roleId/permissions",
    },
  },
  supplier: {
    createSupplier: "/createSupplier",
    detail: "/:supplierId/detail",
    listSuppliers: "/listSuppliers",
    updateSupplier: "/updateSupplier/:id",
    listItems: "/:supplierId/listItems",
    createItem: "/:supplierId/createItem",
    editItem: "/:supplierId/editItem",
    listServices: "/:supplierId/listServices",
    createService: "/:supplierId/createService",
    editService: "/:supplierId/editService",
  },
  pr: {
    list: "/getprs",
    details: "/getprdetails/:id",
    create: "/createpr",
    update: "/updatepr",
    remove: "/deletepr/:id",
    cancelLine: "/:id/lines/:lineId/cancel",
  },
  po: {
    list: "/getpos",
    details: "/getpodetails/:id",
    create: "/createpo",
    update: "/updatepo",
    remove: "/deletepo/:id",
    send: "/:id/send",
    reminder: "/:id/reminder",
    escalate: "/:id/escalate",
    delay: "/:id/delay",
    confirm: "/:id/confirm",
    invoice: "/:id/invoice",
    close: "/:id/close",
    shortClose: "/:id/short-close",
    communications: "/:id/communications",
  },
  grn: {
    list: "/getgrns",
    details: "/getgrndetails/:id",
    create: "/creategrn",
    update: "/updategrn",
    remove: "/deletegrn/:id",
    qaAction: "/:id/lines/:lineId/qa",
    bypass: "/:id/lines/:lineId/bypass",
    correction: "/:id/lines/:lineId/correction",
  },
  approval: {
    getPolicies: "/getPolicies",
    getPolicyDetails: "/getPolicyDetails/:id",
    createPolicy: "/createPolicy",
    updatePolicy: "/updatePolicy/:id",
    submitRequest: "/submitRequest",
    getRequestDetails: "/getRequestDetails/:id",
    getRequestTrail: "/getRequestTrail/:id",
    actOnRequest: "/actOnRequest/:id",
    getMyPendingApprovals: "/getMyPendingApprovals",
    getCurrentApprovalByDoc: "/getCurrentApprovalByDoc/:docType/:docId",
    getApprovalHistory: "/getApprovalHistory/:docType/:docId",
  },
} as const;
